name: Deploy SQL Files

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

on:
  push:
    paths:
      - 'sql/**/*.sql'
  workflow_dispatch:

jobs:
  deploy-sql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install snowsql
        run: |
          set -o pipefail
          sudo apt-get update 2>&1 | tee snowsql_install.log
          sudo apt-get install -y wget jq 2>&1 | tee -a snowsql_install.log
          wget https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.24-linux_x86_64.bash 2>&1 | tee -a snowsql_install.log
          bash snowsql-1.2.24-linux_x86_64.bash 2>&1 | tee -a snowsql_install.log
          export PATH=$PATH:/usr/bin/snowsql
          echo '--- SnowSQL Installation Log ---'
          cat snowsql_install.log
      - name: Deploy SQL files with snowsql
        run: |
          echo "$GA_SECRETS" > ga_secrets.json
          export ACCOUNT=$(jq -r .account ga_secrets.json)
          export USER=$(jq -r .user ga_secrets.json)
          export PASSWORD=$(jq -r .password ga_secrets.json)
          export WAREHOUSE=$(jq -r .warehouse ga_secrets.json)
          export DATABASE=$(jq -r .database ga_secrets.json)
          export SCHEMA=$(jq -r .schema ga_secrets.json)
          export SNOWSQL_LOG_LEVEL=DEBUG
          for file in $(find sql -name '*.sql'); do
            echo "Deploying $file"
            snowsql -a "$ACCOUNT" -u "$USER" -p "$PASSWORD" -w "$WAREHOUSE" -d "$DATABASE" -s "$SCHEMA" -f "$file"
          done
        env:
          GA_SECRETS: ${{ secrets.GA_SECRETS }}
